export const ADMIN_CLASSROOMS_REQUEST = 'ADMIN_CLASSROOMS_REQUEST'
export const ADMIN_CLASSROOMS_SUCCESS = 'ADMIN_CLASSROOMS_SUCCESS'
export const ADMIN_CLASSROOMS_FAIL = 'ADMIN_CLASSROOMS_FAIL'

export const ALL_CLASSROOMS_REQUEST = 'ALL_CLASSROOMS_REQUEST'
export const ALL_CLASSROOMS_SUCCESS = 'ALL_CLASSROOMS_SUCCESS'
export const ALL_CLASSROOMS_FAIL = 'ALL_CLASSROOMS_FAIL'

export const NEW_CLASSROOM_REQUEST = 'NEW_CLASSROOM_REQUEST'
export const NEW_CLASSROOM_SUCCESS = 'NEW_CLASSROOM_SUCCESS'
export const NEW_CLASSROOM_RESET = 'NEW_CLASSROOM_RESET'
export const NEW_CLASSROOM_FAIL = 'NEW_CLASSROOM_FAIL'

export const DELETE_CLASSROOM_REQUEST = 'DELETE_CLASSROOM_REQUEST'
export const DELETE_CLASSROOM_SUCCESS = 'DELETE_CLASSROOM_SUCCESS'
export const DELETE_CLASSROOM_RESET = 'DELETE_CLASSROOM_RESET'
export const DELETE_CLASSROOM_FAIL = 'DELETE_CLASSROOM_FAIL'

export const UPDATE_CLASSROOM_REQUEST = 'UPDATE_CLASSROOM_REQUEST'
export const UPDATE_CLASSROOM_SUCCESS = 'UPDATE_CLASSROOM_SUCCESS'
export const UPDATE_CLASSROOM_RESET = 'UPDATE_CLASSROOM_RESET'
export const UPDATE_CLASSROOM_FAIL = 'UPDATE_CLASSROOM_FAIL'

export const CLASSROOM_DETAILS_REQUEST = 'CLASSROOM_DETAILS_REQUEST'
export const CLASSROOM_DETAILS_SUCCESS = 'CLASSROOM_DETAILS_SUCCESS'
export const CLASSROOM_DETAILS_FAIL = 'CLASSROOM_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'