export const ADMIN_FACILITIES_REQUEST = 'ADMIN_FACILITIES_REQUEST'
export const ADMIN_FACILITIES_SUCCESS = 'ADMIN_FACILITIES_SUCCESS'
export const ADMIN_FACILITIES_FAIL = 'ADMIN_FACILITIES_FAIL'

export const ALL_FACILITIES_REQUEST = 'ALL_FACILITIES_REQUEST'
export const ALL_FACILITIES_SUCCESS = 'ALL_FACILITIES_SUCCESS'
export const ALL_FACILITIES_FAIL = 'ALL_FACILITIES_FAIL'

export const NEW_FACILITY_REQUEST = 'NEW_FACILITY_REQUEST'
export const NEW_FACILITY_SUCCESS = 'NEW_FACILITY_SUCCESS'
export const NEW_FACILITY_RESET = 'NEW_FACILITY_RESET'
export const NEW_FACILITY_FAIL = 'NEW_FACILITY_FAIL'

export const DELETE_FACILITY_REQUEST = 'DELETE_FACILITY_REQUEST'
export const DELETE_FACILITY_SUCCESS = 'DELETE_FACILITY_SUCCESS'
export const DELETE_FACILITY_RESET = 'DELETE_FACILITY_RESET'
export const DELETE_FACILITY_FAIL = 'DELETE_FACILITY_FAIL'

export const UPDATE_FACILITY_REQUEST = 'UPDATE_FACILITY_REQUEST'
export const UPDATE_FACILITY_SUCCESS = 'UPDATE_FACILITY_SUCCESS'
export const UPDATE_FACILITY_RESET = 'UPDATE_FACILITY_RESET'
export const UPDATE_FACILITY_FAIL = 'UPDATE_FACILITY_FAIL'

export const FACILITY_DETAILS_REQUEST = 'FACILITY_DETAILS_REQUEST'
export const FACILITY_DETAILS_SUCCESS = 'FACILITY_DETAILS_SUCCESS'
export const FACILITY_DETAILS_FAIL = 'FACILITY_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'