export const ADMIN_RFIDS_REQUEST = 'ADMIN_RFIDS_REQUEST'
export const ADMIN_RFIDS_SUCCESS = 'ADMIN_RFIDS_SUCCESS'
export const ADMIN_RFIDS_FAIL = 'ADMIN_RFIDS_FAIL'

export const ALL_RFIDS_REQUEST = 'ALL_RFIDS_REQUEST'
export const ALL_RFIDS_SUCCESS = 'ALL_RFIDS_SUCCESS'
export const ALL_RFIDS_FAIL = 'ALL_RFIDS_FAIL'

export const NEW_RFID_REQUEST = 'NEW_RFID_REQUEST'
export const NEW_RFID_SUCCESS = 'NEW_RFID_SUCCESS'
export const NEW_RFID_RESET = 'NEW_RFID_RESET'
export const NEW_RFID_FAIL = 'NEW_RFID_FAIL'

export const DELETE_RFID_REQUEST = 'DELETE_RFID_REQUEST'
export const DELETE_RFID_SUCCESS = 'DELETE_RFID_SUCCESS'
export const DELETE_RFID_RESET = 'DELETE_RFID_RESET'
export const DELETE_RFID_FAIL = 'DELETE_RFID_FAIL'

export const UPDATE_RFID_REQUEST = 'UPDATE_RFID_REQUEST'
export const UPDATE_RFID_SUCCESS = 'UPDATE_RFID_SUCCESS'
export const UPDATE_RFID_RESET = 'UPDATE_RFID_RESET'
export const UPDATE_RFID_FAIL = 'UPDATE_RFID_FAIL'

export const RFID_DETAILS_REQUEST = 'RFID_DETAILS_REQUEST'
export const RFID_DETAILS_SUCCESS = 'RFID_DETAILS_SUCCESS'
export const RFID_DETAILS_FAIL = 'RFID_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'