export const ADMIN_SCHEDULES_REQUEST = 'ADMIN_SCHEDULES_REQUEST'
export const ADMIN_SCHEDULES_SUCCESS = 'ADMIN_SCHEDULES_SUCCESS'
export const ADMIN_SCHEDULES_FAIL = 'ADMIN_SCHEDULES_FAIL'

export const ALL_SCHEDULES_REQUEST = 'ALL_SCHEDULES_REQUEST'
export const ALL_SCHEDULES_SUCCESS = 'ALL_SCHEDULES_SUCCESS'
export const ALL_SCHEDULES_FAIL = 'ALL_SCHEDULES_FAIL'

export const NEW_SCHEDULE_REQUEST = 'NEW_SCHEDULE_REQUEST'
export const NEW_SCHEDULE_SUCCESS = 'NEW_SCHEDULE_SUCCESS'
export const NEW_SCHEDULE_RESET = 'NEW_SCHEDULE_RESET'
export const NEW_SCHEDULE_FAIL = 'NEW_SCHEDULE_FAIL'

export const DELETE_SCHEDULE_REQUEST = 'DELETE_SCHEDULE_REQUEST'
export const DELETE_SCHEDULE_SUCCESS = 'DELETE_SCHEDULE_SUCCESS'
export const DELETE_SCHEDULE_RESET = 'DELETE_SCHEDULE_RESET'
export const DELETE_SCHEDULE_FAIL = 'DELETE_SCHEDULE_FAIL'

export const UPDATE_SCHEDULE_REQUEST = 'UPDATE_SCHEDULE_REQUEST'
export const UPDATE_SCHEDULE_SUCCESS = 'UPDATE_SCHEDULE_SUCCESS'
export const UPDATE_SCHEDULE_RESET = 'UPDATE_SCHEDULE_RESET'
export const UPDATE_SCHEDULE_FAIL = 'UPDATE_SCHEDULE_FAIL'

export const SCHEDULE_DETAILS_REQUEST = 'SCHEDULE_DETAILS_REQUEST'
export const SCHEDULE_DETAILS_SUCCESS = 'SCHEDULE_DETAILS_SUCCESS'
export const SCHEDULE_DETAILS_FAIL = 'SCHEDULE_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const CLEAR_DATA = 'CLEAR_DATA'