export const ADMIN_SECTIONS_REQUEST = 'ADMIN_SECTIONS_REQUEST'
export const ADMIN_SECTIONS_SUCCESS = 'ADMIN_SECTIONS_SUCCESS'
export const ADMIN_SECTIONS_FAIL = 'ADMIN_SECTIONS_FAIL'

export const ALL_SECTIONS_REQUEST = 'ALL_SECTIONS_REQUEST'
export const ALL_SECTIONS_SUCCESS = 'ALL_SECTIONS_SUCCESS'
export const ALL_SECTIONS_FAIL = 'ALL_SECTIONS_FAIL'

export const NEW_SECTION_REQUEST = 'NEW_SECTION_REQUEST'
export const NEW_SECTION_SUCCESS = 'NEW_SECTION_SUCCESS'
export const NEW_SECTION_RESET = 'NEW_SECTION_RESET'
export const NEW_SECTION_FAIL = 'NEW_SECTION_FAIL'

export const DELETE_SECTION_REQUEST = 'DELETE_SECTION_REQUEST'
export const DELETE_SECTION_SUCCESS = 'DELETE_SECTION_SUCCESS'
export const DELETE_SECTION_RESET = 'DELETE_SECTION_RESET'
export const DELETE_SECTION_FAIL = 'DELETE_SECTION_FAIL'

export const UPDATE_SECTION_REQUEST = 'UPDATE_SECTION_REQUEST'
export const UPDATE_SECTION_SUCCESS = 'UPDATE_SECTION_SUCCESS'
export const UPDATE_SECTION_RESET = 'UPDATE_SECTION_RESET'
export const UPDATE_SECTION_FAIL = 'UPDATE_SECTION_FAIL'

export const SECTION_DETAILS_REQUEST = 'SECTION_DETAILS_REQUEST'
export const SECTION_DETAILS_SUCCESS = 'SECTION_DETAILS_SUCCESS'
export const SECTION_DETAILS_FAIL = 'SECTION_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'