export const ADMIN_SUBJECTS_REQUEST = 'ADMIN_SUBJECTS_REQUEST'
export const ADMIN_SUBJECTS_SUCCESS = 'ADMIN_SUBJECTS_SUCCESS'
export const ADMIN_SUBJECTS_FAIL = 'ADMIN_SUBJECTS_FAIL'

export const ALL_SUBJECTS_REQUEST = 'ALL_SUBJECTS_REQUEST'
export const ALL_SUBJECTS_SUCCESS = 'ALL_SUBJECTS_SUCCESS'
export const ALL_SUBJECTS_FAIL = 'ALL_SUBJECTS_FAIL'

export const NEW_SUBJECT_REQUEST = 'NEW_SUBJECT_REQUEST'
export const NEW_SUBJECT_SUCCESS = 'NEW_SUBJECT_SUCCESS'
export const NEW_SUBJECT_RESET = 'NEW_SUBJECT_RESET'
export const NEW_SUBJECT_FAIL = 'NEW_SUBJECT_FAIL'

export const DELETE_SUBJECT_REQUEST = 'DELETE_SUBJECT_REQUEST'
export const DELETE_SUBJECT_SUCCESS = 'DELETE_SUBJECT_SUCCESS'
export const DELETE_SUBJECT_RESET = 'DELETE_SUBJECT_RESET'
export const DELETE_SUBJECT_FAIL = 'DELETE_SUBJECT_FAIL'

export const UPDATE_SUBJECT_REQUEST = 'UPDATE_SUBJECT_REQUEST'
export const UPDATE_SUBJECT_SUCCESS = 'UPDATE_SUBJECT_SUCCESS'
export const UPDATE_SUBJECT_RESET = 'UPDATE_SUBJECT_RESET'
export const UPDATE_SUBJECT_FAIL = 'UPDATE_SUBJECT_FAIL'

export const SUBJECT_DETAILS_REQUEST = 'SUBJECT_DETAILS_REQUEST'
export const SUBJECT_DETAILS_SUCCESS = 'SUBJECT_DETAILS_SUCCESS'
export const SUBJECT_DETAILS_FAIL = 'SUBJECT_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'