export const ADMIN_TEMPERATURES_REQUEST = 'ADMIN_TEMPERATURES_REQUEST'
export const ADMIN_TEMPERATURES_SUCCESS = 'ADMIN_TEMPERATURES_SUCCESS'
export const ADMIN_TEMPERATURES_FAIL = 'ADMIN_TEMPERATURES_FAIL'

export const ALL_TEMPERATURES_REQUEST = 'ALL_TEMPERATURES_REQUEST'
export const ALL_TEMPERATURES_SUCCESS = 'ALL_TEMPERATURES_SUCCESS'
export const ALL_TEMPERATURES_FAIL = 'ALL_TEMPERATURES_FAIL'

export const NEW_TEMPERATURE_REQUEST = 'NEW_TEMPERATURE_REQUEST'
export const NEW_TEMPERATURE_SUCCESS = 'NEW_TEMPERATURE_SUCCESS'
export const NEW_TEMPERATURE_RESET = 'NEW_TEMPERATURE_RESET'
export const NEW_TEMPERATURE_FAIL = 'NEW_TEMPERATURE_FAIL'

export const DELETE_TEMPERATURE_REQUEST = 'DELETE_TEMPERATURE_REQUEST'
export const DELETE_TEMPERATURE_SUCCESS = 'DELETE_TEMPERATURE_SUCCESS'
export const DELETE_TEMPERATURE_RESET = 'DELETE_TEMPERATURE_RESET'
export const DELETE_TEMPERATURE_FAIL = 'DELETE_TEMPERATURE_FAIL'

export const UPDATE_TEMPERATURE_REQUEST = 'UPDATE_TEMPERATURE_REQUEST'
export const UPDATE_TEMPERATURE_SUCCESS = 'UPDATE_TEMPERATURE_SUCCESS'
export const UPDATE_TEMPERATURE_RESET = 'UPDATE_TEMPERATURE_RESET'
export const UPDATE_TEMPERATURE_FAIL = 'UPDATE_TEMPERATURE_FAIL'

export const TEMPERATURE_DETAILS_REQUEST = 'TEMPERATURE_DETAILS_REQUEST'
export const TEMPERATURE_DETAILS_SUCCESS = 'TEMPERATURE_DETAILS_SUCCESS'
export const TEMPERATURE_DETAILS_FAIL = 'TEMPERATURE_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'