export const ADMIN_TICKETS_REQUEST = 'ADMIN_TICKETS_REQUEST'
export const ADMIN_TICKETS_SUCCESS = 'ADMIN_TICKETS_SUCCESS'
export const ADMIN_TICKETS_FAIL = 'ADMIN_TICKETS_FAIL'

export const ALL_TICKETS_REQUEST = 'ALL_TICKETS_REQUEST'
export const ALL_TICKETS_SUCCESS = 'ALL_TICKETS_SUCCESS'
export const ALL_TICKETS_FAIL = 'ALL_TICKETS_FAIL'

export const NEW_TICKET_REQUEST = 'NEW_TICKET_REQUEST'
export const NEW_TICKET_SUCCESS = 'NEW_TICKET_SUCCESS'
export const NEW_TICKET_RESET = 'NEW_TICKET_RESET'
export const NEW_TICKET_FAIL = 'NEW_TICKET_FAIL'

export const DELETE_TICKET_REQUEST = 'DELETE_TICKET_REQUEST'
export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS'
export const DELETE_TICKET_RESET = 'DELETE_TICKET_RESET'
export const DELETE_TICKET_FAIL = 'DELETE_TICKET_FAIL'

export const UPDATE_TICKET_REQUEST = 'UPDATE_TICKET_REQUEST'
export const UPDATE_TICKET_SUCCESS = 'UPDATE_TICKET_SUCCESS'
export const UPDATE_TICKET_RESET = 'UPDATE_TICKET_RESET'
export const UPDATE_TICKET_FAIL = 'UPDATE_TICKET_FAIL'

export const TICKET_DETAILS_REQUEST = 'TICKET_DETAILS_REQUEST'
export const TICKET_DETAILS_SUCCESS = 'TICKET_DETAILS_SUCCESS'
export const TICKET_DETAILS_FAIL = 'TICKET_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'